<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Generate the loan statement PDF file
require_once('fpdf/fpdf.php');

class PDF extends FPDF {
    function Header() {
        // header information
        $this->SetTitle('Loan Statement');
    }

    function Footer() {
        // footer information
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by Tera Microfinance', 0, 0, 'C');
    }
}

// Get the loan statement data from the database
include_once "dbconfig.php";
$user_logged_in = $_SESSION['username'];
$sql = "SELECT * FROM loans WHERE username='$user_logged_in'";
$result = $database_connection->query($sql);

// Generate the loan statement PDF file
if ($result->num_rows > 0) {
    $pdf = new PDF();
    $pdf->AliasNbPages();
    $pdf->AddPage();

    // Set the font and font size for the content
    $pdf->SetFont('Arial', '', 12);

    // Output the loan statement content
    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(0, 10, 'Username: ' . $row['username'], 0, 1);
        $pdf->Cell(0, 10, 'Amount Due: ' . $row['amount_due'], 0, 1);
        $pdf->Cell(0, 10, 'Date Due: ' . $row['due_date'], 0, 1);
        $pdf->Cell(0, 10, 'Loan Status: ' . $row['status'], 0, 1);
        $pdf->Ln(10); // Add a line break between each entry
    }

    // Save the loan statement PDF file
    $pdfFilename = "Loan Statement.pdf";
    $pdf->Output('F', $pdfFilename);

    // Send the file to the browser for download
    header('Content-type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $pdfFilename . '"');
    readfile($pdfFilename);
} elseif ($result->num_rows == 0) {
    echo "No Loan Data";
} else {
    echo "No Unpaid Loan";
}
?>
